/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thassingment;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author chamith
 */
public class courseSelectM extends javax.swing.JFrame {
    static String underComCourse;
    static String underBuiCourse;
    static String postComCourse;
    static String underEngCourse;
    static String postBuiCourse;
    static String postEngiCourse;
    static String alSub1;
    static String alSub2;
    static String alSub3;
    static String alZscore;
    static String alSub1R;
    static String alSub2R;
    static String alSub3R;
    static String gEngR;
    static String stream ;
    static String pInstitute;
    static String pDegree;
    static String facultyid;
    static String status;
    static int alyear;
    static int postYear;
    static String gpa;
    
  
    
    
    

    /**
     * Creates new form courseSelectM
     */
    public courseSelectM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        underPostTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        facultyTabbedPane = new javax.swing.JTabbedPane();
        underSOC = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        underComputerList = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        underBuisnessList = new javax.swing.JList<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        underEngineeringList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        alStreamCombo = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        alSub1Txt = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        alSub2Txt = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        alSub3Txt = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        alSub1Combo = new javax.swing.JComboBox<>();
        alSub2Combo = new javax.swing.JComboBox<>();
        alSub3Combo = new javax.swing.JComboBox<>();
        genEngCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        alYearChooser = new com.toedter.calendar.JYearChooser();
        alZText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        PostEngineeringList = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        postComputingList = new javax.swing.JList<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        postBuiList = new javax.swing.JList<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        postEngCourse = new javax.swing.JList<>();
        jPanel139 = new javax.swing.JPanel();
        jScrollPane397 = new javax.swing.JScrollPane();
        postInstituteText = new javax.swing.JTextPane();
        jScrollPane398 = new javax.swing.JScrollPane();
        postDegreeText = new javax.swing.JTextPane();
        jLabel528 = new javax.swing.JLabel();
        jLabel529 = new javax.swing.JLabel();
        postYearText = new com.toedter.calendar.JYearChooser();
        jLabel530 = new javax.swing.JLabel();
        jLabel531 = new javax.swing.JLabel();
        jScrollPane399 = new javax.swing.JScrollPane();
        postGpaText = new javax.swing.JTextPane();
        nextJbtn = new javax.swing.JButton();
        resetJbtn = new javax.swing.JButton();
        backJbtn = new javax.swing.JButton();
        exitJbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Andika", 1, 24)); // NOI18N
        jLabel1.setText("Select the Course");

        underPostTabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        underPostTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        underPostTabbedPane.setFont(new java.awt.Font("Andika", 1, 24)); // NOI18N

        facultyTabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        facultyTabbedPane.setFont(new java.awt.Font("Andika", 0, 24)); // NOI18N

        underSOC.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, java.awt.Color.gray), "School Of Computing", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andika", 1, 24))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Andika", 1, 24)); // NOI18N
        jLabel3.setText("Bachelor Courses");

        underComputerList.setBackground(new java.awt.Color(242, 241, 240));
        underComputerList.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        underComputerList.setForeground(new java.awt.Color(76, 76, 76));
        underComputerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bsc(Special) Management Information Systems", "Bsc (Honurs) in Computer Science", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        underComputerList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        underComputerList.setSelectionForeground(new java.awt.Color(242, 241, 240));
        jScrollPane1.setViewportView(underComputerList);

        javax.swing.GroupLayout underSOCLayout = new javax.swing.GroupLayout(underSOC);
        underSOC.setLayout(underSOCLayout);
        underSOCLayout.setHorizontalGroup(
            underSOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(underSOCLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        underSOCLayout.setVerticalGroup(
            underSOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(underSOCLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, underSOCLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        facultyTabbedPane.addTab("School Of Computing", underSOC);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, java.awt.Color.gray), "School of Buisness", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andika", 1, 24))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Andika", 1, 24)); // NOI18N
        jLabel4.setText("Bachelor Courses");

        underBuisnessList.setBackground(new java.awt.Color(242, 241, 240));
        underBuisnessList.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        underBuisnessList.setForeground(new java.awt.Color(76, 76, 76));
        underBuisnessList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BSc in Business Management (Human Resource Management) (Special)", "BSc in Business Management (Project Management) (Special)", "BA in Business Communication" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        underBuisnessList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        underBuisnessList.setSelectionForeground(new java.awt.Color(242, 241, 240));
        jScrollPane2.setViewportView(underBuisnessList);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        facultyTabbedPane.addTab("School of Buisness", jPanel9);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, java.awt.Color.gray), "School of Engineering", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andika", 1, 24))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Andika", 1, 24)); // NOI18N
        jLabel5.setText("Bachelor Courses");

        underEngineeringList.setBackground(new java.awt.Color(242, 241, 240));
        underEngineeringList.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        underEngineeringList.setForeground(new java.awt.Color(76, 76, 76));
        underEngineeringList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BSc (Honours) Engineering in Computer Systems Engineering" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        underEngineeringList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        underEngineeringList.setSelectionForeground(new java.awt.Color(242, 241, 240));
        jScrollPane3.setViewportView(underEngineeringList);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        facultyTabbedPane.addTab("School of Engineering", jPanel8);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Enter GCE A/L results", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andika", 1, 24))); // NOI18N

        alStreamCombo.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        alStreamCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical Science", "biology", "Commerce", "Arts", "Technical" }));
        alStreamCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alStreamComboActionPerformed(evt);
            }
        });

        alSub1Txt.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        alSub1Txt.setText("Subject 1");
        alSub1Txt.setAutoscrolls(false);
        jScrollPane7.setViewportView(alSub1Txt);

        alSub2Txt.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        alSub2Txt.setText("Subject 2");
        alSub2Txt.setAutoscrolls(false);
        jScrollPane8.setViewportView(alSub2Txt);

        alSub3Txt.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        alSub3Txt.setText("Subject 3");
        alSub3Txt.setAutoscrolls(false);
        jScrollPane9.setViewportView(alSub3Txt);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("General English");

        alSub1Combo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        alSub1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "S", "F" }));
        alSub1Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alSub1ComboActionPerformed(evt);
            }
        });

        alSub2Combo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        alSub2Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "S", "F" }));

        alSub3Combo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        alSub3Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "S", "F" }));

        genEngCombo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        genEngCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "S", "F" }));
        genEngCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genEngComboActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel9.setText("Year");

        jLabel10.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel10.setText("Z score");

        alZText.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane9)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(alSub3Combo, javax.swing.GroupLayout.Alignment.LEADING, 0, 74, Short.MAX_VALUE)
                    .addComponent(alSub2Combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alSub1Combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genEngCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alZText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(alStreamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(alStreamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alSub1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(alZText)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(alYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(alSub2Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alSub3Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genEngCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(facultyTabbedPane)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(facultyTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(293, Short.MAX_VALUE)))
        );

        underPostTabbedPane.addTab("Undergraduate", jPanel1);

        PostEngineeringList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PostEngineeringList.setFont(new java.awt.Font("Andika", 0, 24)); // NOI18N

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, java.awt.Color.gray), "School Of Computing", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andika", 1, 24))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Andika", 1, 24)); // NOI18N
        jLabel6.setText("Master Courses");

        postComputingList.setBackground(new java.awt.Color(242, 241, 240));
        postComputingList.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        postComputingList.setForeground(new java.awt.Color(76, 76, 76));
        postComputingList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Postgraduate Diploma in Computer Networks" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        postComputingList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        postComputingList.setSelectionForeground(new java.awt.Color(242, 241, 240));
        jScrollPane4.setViewportView(postComputingList);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        PostEngineeringList.addTab("School Of Computing", jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, java.awt.Color.gray), "School of Buisness", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andika", 1, 24))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Andika", 1, 24)); // NOI18N
        jLabel7.setText("Master Courses");

        postBuiList.setBackground(new java.awt.Color(242, 241, 240));
        postBuiList.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        postBuiList.setForeground(new java.awt.Color(76, 76, 76));
        postBuiList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Postgraduate Diploma in Human Resource Management", "Postgraduate Diploma in Business Management", "Master of Business Administration" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        postBuiList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        postBuiList.setSelectionForeground(new java.awt.Color(242, 241, 240));
        jScrollPane5.setViewportView(postBuiList);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        PostEngineeringList.addTab("School of Buisness", jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, java.awt.Color.gray), "School of Engineering", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andika", 1, 24))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Andika", 1, 24)); // NOI18N
        jLabel8.setText("Master Courses");

        postEngCourse.setBackground(new java.awt.Color(242, 241, 240));
        postEngCourse.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        postEngCourse.setForeground(new java.awt.Color(76, 76, 76));
        postEngCourse.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Masters Mechatronics Engineering", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        postEngCourse.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        postEngCourse.setSelectionForeground(new java.awt.Color(242, 241, 240));
        jScrollPane6.setViewportView(postEngCourse);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        PostEngineeringList.addTab("School of Engineering", jPanel12);

        jPanel139.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Enter Qualifications", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andika", 1, 24))); // NOI18N

        postInstituteText.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jScrollPane397.setViewportView(postInstituteText);

        postDegreeText.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jScrollPane398.setViewportView(postDegreeText);

        jLabel528.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel528.setText("Degree");

        jLabel529.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel529.setText("Institue");

        jLabel530.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel530.setText("Year");

        jLabel531.setFont(new java.awt.Font("Andika", 1, 18)); // NOI18N
        jLabel531.setText("Gpa");

        postGpaText.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jScrollPane399.setViewportView(postGpaText);

        javax.swing.GroupLayout jPanel139Layout = new javax.swing.GroupLayout(jPanel139);
        jPanel139.setLayout(jPanel139Layout);
        jPanel139Layout.setHorizontalGroup(
            jPanel139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel139Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel139Layout.createSequentialGroup()
                        .addComponent(jLabel530, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel139Layout.createSequentialGroup()
                        .addGroup(jPanel139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel529, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel528, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel139Layout.createSequentialGroup()
                            .addComponent(jScrollPane398, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel139Layout.createSequentialGroup()
                            .addComponent(jScrollPane397, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                            .addComponent(jLabel531, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane399, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel139Layout.createSequentialGroup()
                        .addComponent(postYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(809, Short.MAX_VALUE))))
        );
        jPanel139Layout.setVerticalGroup(
            jPanel139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel139Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel139Layout.createSequentialGroup()
                        .addGroup(jPanel139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel529, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane397, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addComponent(jLabel531, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane399, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane398, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel528, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel530, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PostEngineeringList)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(jPanel139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PostEngineeringList, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(293, Short.MAX_VALUE)))
        );

        underPostTabbedPane.addTab("Postgraduate", jPanel3);

        nextJbtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        nextJbtn.setText("Next");
        nextJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJbtnActionPerformed(evt);
            }
        });

        resetJbtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        resetJbtn.setText("Reset");
        resetJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetJbtnActionPerformed(evt);
            }
        });

        backJbtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        backJbtn.setText("Back");

        exitJbtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        exitJbtn.setText("Exit");
        exitJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(underPostTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(nextJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(resetJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underPostTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nextJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genEngComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genEngComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genEngComboActionPerformed

    private void nextJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJbtnActionPerformed
        // TODO add your handling code here:
        boolean bUnCom=underComputerList.isSelectionEmpty();
        boolean bUnBui=underComputerList.isSelectionEmpty();
        boolean bUnEng=underComputerList.isSelectionEmpty();
        boolean bPoCom=underComputerList.isSelectionEmpty();
        boolean bPoBui=underComputerList.isSelectionEmpty();
        boolean bPoEng=underComputerList.isSelectionEmpty();
        System.out.println(bUnCom);
        
        if(bUnCom==false){
            underComCourse = underComputerList.getSelectedValue();
        }
        if(bUnBui==false){
        underBuiCourse = underBuisnessList.getSelectedValue();
        }
        if(bUnEng==false){
        underEngCourse = underEngineeringList.getSelectedValue();
        }
        if(bPoCom==false){
        postComCourse = postComputingList.getSelectedValue();
        }
        if(bPoBui==false){
        postBuiCourse = postBuiList.getSelectedValue();
        }
        if(bPoEng==false){
        postEngiCourse = postEngCourse.getSelectedValue();
        }
        
        if(bUnCom==false || bUnBui==false ||bUnEng==false){
            alSub1 = alSub1Txt.getText();
            alSub2 = alSub2Txt.getText();
            alSub3 = alSub3Txt.getText();
            alZscore = alZText.getText();
            alSub1R= (String) alSub1Combo.getSelectedItem();
            alSub2R= (String) alSub2Combo.getSelectedItem();
            alSub3R = (String) alSub3Combo.getSelectedItem();
            gEngR = (String) genEngCombo.getSelectedItem();
            stream = (String) alStreamCombo.getSelectedItem();
            alyear=(int)alYearChooser.getYear();
        }
        
        if(bPoCom==false || bPoBui==false ||bPoEng==false){
            pInstitute = postInstituteText.getText();
            pDegree = postDegreeText.getText();
            gpa =postGpaText.getText();
            postYear=(int)postYearText.getYear();
        }
        

        
        if(bUnCom==false || bPoCom==false){
            facultyid="Com";   
        }
        else if(bUnBui==false || bPoBui==false){
            facultyid="Bui";
        }
        else if(bUnEng==false || bPoEng==false){
            facultyid="Eng";
        }
        
        
        if(bUnCom==false || bUnBui==false ||bUnEng==false){
            status="undergraduate";
        }
        else if(bPoCom==false || bPoBui==false ||bPoEng==false){
            status="postgraduate";
        }
        close();
        MStudentDe MStuDe=new MStudentDe();
        MStuDe.setVisible(true);
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_nextJbtnActionPerformed

    private void alStreamComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alStreamComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alStreamComboActionPerformed

    private void resetJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetJbtnActionPerformed
        underComputerList.clearSelection();
        underBuisnessList.clearSelection();
        underEngineeringList.clearSelection();
        postComputingList.clearSelection();
        postBuiList.clearSelection();
        postEngCourse.clearSelection();
        postInstituteText.setText(null);
        postGpaText.setText(null);
        alYearChooser.setYear(2018);
        postYearText.setYear(2018);
        postDegreeText.setText(null);
        alSub1Txt.setText(null);
        alSub2Txt.setText(null);
        alSub3Txt.setText(null);
        alZText.setText(null);
        
    }//GEN-LAST:event_resetJbtnActionPerformed

    private void exitJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitJbtnActionPerformed

    private void alSub1ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alSub1ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alSub1ComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courseSelectM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courseSelectM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courseSelectM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courseSelectM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new courseSelectM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PostEngineeringList;
    private javax.swing.JComboBox<String> alStreamCombo;
    private javax.swing.JComboBox<String> alSub1Combo;
    private javax.swing.JTextPane alSub1Txt;
    private javax.swing.JComboBox<String> alSub2Combo;
    private javax.swing.JTextPane alSub2Txt;
    private javax.swing.JComboBox<String> alSub3Combo;
    private javax.swing.JTextPane alSub3Txt;
    private com.toedter.calendar.JYearChooser alYearChooser;
    private javax.swing.JTextField alZText;
    private javax.swing.JButton backJbtn;
    private javax.swing.JButton exitJbtn;
    private javax.swing.JTabbedPane facultyTabbedPane;
    private javax.swing.JComboBox<String> genEngCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel528;
    private javax.swing.JLabel jLabel529;
    private javax.swing.JLabel jLabel530;
    private javax.swing.JLabel jLabel531;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel139;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane397;
    private javax.swing.JScrollPane jScrollPane398;
    private javax.swing.JScrollPane jScrollPane399;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton nextJbtn;
    private javax.swing.JList<String> postBuiList;
    private javax.swing.JList<String> postComputingList;
    private javax.swing.JTextPane postDegreeText;
    private javax.swing.JList<String> postEngCourse;
    private javax.swing.JTextPane postGpaText;
    private javax.swing.JTextPane postInstituteText;
    private com.toedter.calendar.JYearChooser postYearText;
    private javax.swing.JButton resetJbtn;
    private javax.swing.JList<String> underBuisnessList;
    private javax.swing.JList<String> underComputerList;
    private javax.swing.JList<String> underEngineeringList;
    private javax.swing.JTabbedPane underPostTabbedPane;
    private javax.swing.JPanel underSOC;
    // End of variables declaration//GEN-END:variables
    public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }
    
    private void SystemExit(){
        WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        
    }

}

