/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thassingment;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static thassingment.ManageSubject.subId;

/**
 *
 * @author chamith
 */
public class ManAssingments extends javax.swing.JFrame {
    
    PreparedStatement pst=null;
     PreparedStatement pst2=null;
      PreparedStatement pst3=null;
    Connection conn=null;
    Statement statement=null;
    ResultSet rs = null;
    ResultSet rs2 = null;
    ResultSet rs3= null;
    String course="ComputerScience";
    static String AssingId;
    static String CourseId;
    static String SubId;
    static String type;
    static Date Da;
    static java.sql.Date sdate;
    static String timeslot;
    static String AID;
    Assingments a1=new Assingments();
    
public void coursecombo(){
        try{
            conn=MySqlConnect.ConnectDB();
            String sql="SELECT `CourseId` FROM `underCourse`";
        //   String sql2="SELECT `CourseId` FROM `postCourse`";
             
             
            pst=conn.prepareStatement(sql);
         //   pst2=conn.prepareStatement(sql2);

          rs=pst.executeQuery();
        //  rs2=pst2.executeQuery();
         
        while (rs.next()) {
            jcoursecombo.addItem(rs.getString("CourseId"));
        }
       //while (rs2.next()) {
         //   jcoursecombo.addItem(rs2.getString("CourseId"));
       // }
          //  JOptionPane.showMessageDialog(null,"");   
            }
            catch(Exception e){
                    JOptionPane.showMessageDialog(null,e); 
                    }
}
        public void coursecombo2(){
        try{
            conn=MySqlConnect.ConnectDB();
           // String sql="SELECT `CourseId` FROM `underCourse`";
           String sql2="SELECT `CourseId` FROM `postCourse`";
             
             
           // pst=conn.prepareStatement(sql);
            pst2=conn.prepareStatement(sql2);

         // rs=pst.executeQuery();
          rs2=pst2.executeQuery();
         
       // while (rs.next()) {
       //     jcoursecombo.addItem(rs.getString("CourseId"));
       // }
        while (rs2.next()) {
            jcoursecombo.addItem(rs2.getString("CourseId"));
        }
          //  JOptionPane.showMessageDialog(null,"");   
            }
            catch(Exception e){
                    JOptionPane.showMessageDialog(null,e); 
                    }
           /* finally{
            try{
                //pst.close();
              //  rs.close();
               // conn.close();
                pst2.close();
                rs2.close();
               
            } catch (SQLException ex) {
                Logger.getLogger(ManageSubject.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/

    }

public void subsem1combo1(){
        try{
            conn=MySqlConnect.ConnectDB();
            String sql="SELECT `subjectid` FROM `subject` WHERE CourseId=?";
             
            pst3=conn.prepareStatement(sql);
             pst3.setString(1,course);

           rs3=pst3.executeQuery();
         
        while (rs3.next()) {
            jsubcombo.addItem(rs3.getString("subjectid"));
            
        
        }
          //  JOptionPane.showMessageDialog(null,"");   
            }
            catch(Exception e){
                    JOptionPane.showMessageDialog(null,e); 
                    }
         /*   finally{
            try{
                pst.close();
                rs.close();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(ManageSubject.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/

    }
    public ManAssingments() {
        initComponents();
        a1.fillassingTable(jTable1,"");
        coursecombo();
        coursecombo2();
        
        
     //   jcoursecombo.setSelectedIndex(-1);
      //  subsem1combo1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jjassingIDtext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jAstypecombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jsubcombo = new javax.swing.JComboBox<>();
        jasDateChooser = new com.toedter.calendar.JDateChooser();
        Jtimetxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcoursecombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        AsInsertbtn = new javax.swing.JButton();
        AsUpdatebtn = new javax.swing.JButton();
        Asdeletebtn = new javax.swing.JButton();
        jsearchtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Assingment Detais");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("SubjectID");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Type");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("AssingmentID");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Time Slot");

        jAstypecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In class Practical", "In class written", "Takehome" }));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Date");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AsingmentId", "CourseId", "SubjectId", "Type", "Date", "TimeSlot"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jcoursecombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcoursecomboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jcoursecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcoursecomboActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("CourseId");

        AsInsertbtn.setText("Insert");
        AsInsertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsInsertbtnActionPerformed(evt);
            }
        });

        AsUpdatebtn.setText("Update");
        AsUpdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsUpdatebtnActionPerformed(evt);
            }
        });

        Asdeletebtn.setText("Delete");
        Asdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsdeletebtnActionPerformed(evt);
            }
        });

        jsearchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsearchtxtKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("Enter value to Search");

        Exitbtn.setText("Exit");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jjassingIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AsInsertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Jtimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jasDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jAstypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(AsUpdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jsubcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcoursecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jsearchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(Asdeletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(143, 143, 143)
                                        .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jjassingIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jsearchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcoursecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jsubcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAstypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jasDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jtimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(AsInsertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Asdeletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AsUpdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcoursecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcoursecomboActionPerformed
      course=(String) jcoursecombo.getSelectedItem();
      System.out.println(course);
      System.out.println(jcoursecombo.getSelectedIndex());
      jsubcombo.removeAllItems();
      subsem1combo1();
    }//GEN-LAST:event_jcoursecomboActionPerformed

    private void jcoursecomboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcoursecomboPopupMenuWillBecomeInvisible
     // course=(String) jcoursecombo.getSelectedItem();
     // System.out.println(course);
      //System.out.println(jcoursecombo.getSelectedIndex());
      //jsubcombo.removeAllItems();
     // subsem1combo1();
    }//GEN-LAST:event_jcoursecomboPopupMenuWillBecomeInvisible

    private void AsInsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsInsertbtnActionPerformed
    AssingId=jjassingIDtext.getText();
   CourseId=(String) jcoursecombo.getSelectedItem();
    SubId=(String) jsubcombo.getSelectedItem();
    type=(String) jAstypecombo.getSelectedItem();
       jasDateChooser.setDateFormatString("dd/MM/yyyy");
       Da=jasDateChooser.getDate();
       java.sql.Date sqlDate = new java.sql.Date(Da.getTime());
       sdate=sqlDate;
       timeslot=Jtimetxt.getText();
       
       a1.Assingmentinsert();
       DefaultTableModel model3=(DefaultTableModel)jTable1.getModel();//Resetting the table
       model3.setRowCount(0);
      a1.fillassingTable(jTable1,"");
    }//GEN-LAST:event_AsInsertbtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                              int rowIndex=jTable1.getSelectedRow();
        DefaultTableModel model1=(DefaultTableModel) jTable1.getModel();
      AID=(model1.getValueAt(rowIndex,0).toString());
        jjassingIDtext.setText(model1.getValueAt(rowIndex,0).toString());
        jcoursecombo.setSelectedItem(model1.getValueAt(rowIndex,1).toString());
        jsubcombo.setSelectedItem(model1.getValueAt(rowIndex,2).toString());
        jAstypecombo.setSelectedItem(model1.getValueAt(rowIndex,3).toString());
        
        Jtimetxt.setText(model1.getValueAt(rowIndex,5).toString());
          Date bdate;
        try {
            bdate=new SimpleDateFormat("yyyy-MM-dd").parse(model1.getValueAt(rowIndex,4).toString());
            System.out.println(bdate);
            jasDateChooser.setDate(bdate);           
              } catch (ParseException ex) {
            Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void AsUpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsUpdatebtnActionPerformed
           AssingId=jjassingIDtext.getText();
        CourseId=(String) jcoursecombo.getSelectedItem();
         SubId=(String) jsubcombo.getSelectedItem();
        type=(String) jAstypecombo.getSelectedItem();
       jasDateChooser.setDateFormatString("dd/MM/yyyy");
       Da=jasDateChooser.getDate();
       java.sql.Date sqlDate = new java.sql.Date(Da.getTime());
       sdate=sqlDate;
       timeslot=Jtimetxt.getText();
       
       a1.asinUpdate();
       DefaultTableModel model4=(DefaultTableModel)jTable1.getModel();//Resetting the table
       model4.setRowCount(0);
      a1.fillassingTable(jTable1,"");
    }//GEN-LAST:event_AsUpdatebtnActionPerformed

    private void AsdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsdeletebtnActionPerformed
       a1.asinDelete();
       DefaultTableModel model5=(DefaultTableModel)jTable1.getModel();//Resetting the table
       model5.setRowCount(0);
      a1.fillassingTable(jTable1,"");
    }//GEN-LAST:event_AsdeletebtnActionPerformed

    private void jsearchtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsearchtxtKeyPressed
        jTable1.setModel(new DefaultTableModel(null,new Object []{"AssingmentId","CourseId","SubjectId","Type","Date","TimeSlot"}));
        a1.fillassingTable(jTable1,jsearchtxt.getText()); 
    }//GEN-LAST:event_jsearchtxtKeyPressed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
       close();
    }//GEN-LAST:event_ExitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManAssingments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManAssingments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManAssingments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManAssingments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManAssingments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsInsertbtn;
    private javax.swing.JButton AsUpdatebtn;
    private javax.swing.JButton Asdeletebtn;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JTextField Jtimetxt;
    private javax.swing.JComboBox<String> jAstypecombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jasDateChooser;
    private javax.swing.JComboBox<String> jcoursecombo;
    private javax.swing.JTextField jjassingIDtext;
    private javax.swing.JTextField jsearchtxt;
    private javax.swing.JComboBox<String> jsubcombo;
    // End of variables declaration//GEN-END:variables
    private void SystemExit(){
        WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        
    }
    public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }

}
