/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thassingment;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author chamith
 */
public class SubSelect extends javax.swing.JFrame {

    /**
     * Creates new form SubSelect
     */
    static String S1Sub1;
    static String S1Sub2;
    static String S1Sub3;
    static String S1Sub4;
    static String S2Sub1;
    static String S2Sub2;
    static String S2Sub3;
    static String S2Sub4;
    
    
    PreparedStatement pst=null;
    Connection conn=null;
    
    ArrayList<String> items=new ArrayList<String>();
   DefaultListModel dlm = new DefaultListModel();
   DefaultListModel dlm2 = new DefaultListModel();
   
   
    
    public SubSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Sem1SubList = new javax.swing.JList<>();
        Sem1SubList.setSelectionModel(new MySelectionModel(Sem1SubList, 4));
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Sem2Sublist = new javax.swing.JList<>();
        Sem1SubList.setSelectionModel(new MySelectionModel(Sem1SubList, 4));
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Andika", 1, 24)); // NOI18N
        jLabel1.setText("Select subjects");

        Sem1SubList.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Sem1SubList.setToolTipText("");
        jScrollPane1.setViewportView(Sem1SubList);

        jLabel2.setFont(new java.awt.Font("Andika", 0, 24)); // NOI18N
        jLabel2.setText("Select 4 Subjects  for Semester 1");

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton2.setText("Back");

        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton3.setText("Exit");

        jButton4.setText("Generate subjects");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Sem2Sublist.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Sem2Sublist.setToolTipText("");
        jScrollPane2.setViewportView(Sem2Sublist);

        jLabel3.setFont(new java.awt.Font("Andika", 0, 24)); // NOI18N
        jLabel3.setText("Select 4 Subjects  for Semester 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 

    
    public void setlistCS(){
         Sem1SubList.setModel(dlm);
         dlm.addElement("Computer Architecture");
         dlm.addElement("Web Based Application Development");
         dlm.addElement("Object Oriented Programming with Java");
         dlm.addElement("Professional Development ");
         dlm.addElement("Data communications and networks");
         
    }
    
    public void setlistCS2(){
         Sem2Sublist.setModel(dlm2);
         dlm2.addElement("Computer Networks");
         dlm2.addElement("Systems Analysis and Design ");
         dlm2.addElement("Operating Systems ");
         dlm2.addElement("Mathematics II ");
     //    dlm2.addElement("Introduction to Software Engineering ");
         
    }
    
    
    public void setListIS(){
                 Sem1SubList.setModel(dlm);
         dlm.addElement("Computer Architecture");
         dlm.addElement("Web Based Application Development");
         dlm.addElement("Object Oriented Programming with Java");
         dlm.addElement("Professional Development ");
         dlm.addElement("Data communications and networks");
  
    }
    
    
        public void setlistHRM(){
         Sem1SubList.setModel(dlm);
         dlm.addElement("Management Process");
         dlm.addElement("Business Communication");
         dlm.addElement("Financial Accounting");
         dlm.addElement("Managerial Accounting");
         dlm.addElement("Buisness Environment");
         
    }

    private static class MySelectionModel extends DefaultListSelectionModel
            
{
    private javax.swing.JList SemSubList;
    private int maxCount;

    private MySelectionModel(javax.swing.JList SemSubList,int maxCount)
    {
        this.SemSubList = SemSubList;

        this.maxCount = maxCount;
    }

    @Override
    public void setSelectionInterval(int index0, int index1)
    {
        if (index1 - index0 >= maxCount)
        {
            index1 = index0 + maxCount - 1;
        }
        super.setSelectionInterval(index0, index1);
    }

    @Override
    public void addSelectionInterval(int index0, int index1)
    {
        int selectionLength = SemSubList.getSelectedIndices().length;
        if (selectionLength >= maxCount)
            return;

        if (index1 - index0 >= maxCount - selectionLength)
        {
            index1 = index0 + maxCount - 1 - selectionLength;
        }
        if (index1 < index0)
            return;
        super.addSelectionInterval(index0, index1);
    }
    
    
    
}
    

    /*PreparedStatement pst=null;
    ResultSet rs = null;
    Connection conn=null;
    
    
public void populateJList(JList Sem1SubList, String query, Connection conn) throws SQLException
{
    DefaultListModel model = new DefaultListModel(); //create a new list model

    Statement statement = conn.createStatement();
    ResultSet resultSet = statement.executeQuery(query); //run your query

    while (resultSet.next()) //go through each row that your query returns
    {
        String itemCode = resultSet.getString("item_code"); //get the element in column "item_code"
        model.addElement(itemCode); //add each item to the model
    }
    Sem1SubList.setModel(model);

    resultSet.close();
    statement.close();

}
    */
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Object[] selected =Sem1SubList.getSelectedValues();

        String[] selectedItems = new String[selected.length];
        
        for(int i=0; i<selected.length;i++){
            selectedItems[i] = selected[i].toString();
    }
        
        S1Sub1= selectedItems[0];
        S1Sub2= selectedItems[1];
        S1Sub3= selectedItems[2];
        S1Sub4= selectedItems[3];
       if(MStudentDe.intakeBtnGroup1=="July"){  
        Object[] selected2 =Sem2Sublist.getSelectedValues();

        String[] selectedItems2 = new String[selected2.length];
        
        for(int i=0; i<selected2.length;i++){
            selectedItems2[i] = selected2[i].toString();
    }
        
        S2Sub1= selectedItems2[0];
        S2Sub2= selectedItems2[1];
        S2Sub3= selectedItems2[2];
        S2Sub4= selectedItems2[3];
        
       }  
        System.out.println("sem 1 "+S1Sub1);
        System.out.println("sem 2 "+S2Sub1);
        System.out.println("sem 2 "+S2Sub2);
        StudentInsert s1=new StudentInsert();
        
        if (courseSelectM.status=="Undergraduate"){
                s1.UnderStuInsert();
                s1.Alinsert();
                if(MStudentDe.intakeBtnGroup1=="February"){
                    s1.subinsert1();
                }
                else {
                    s1.subinsert1();
                    s1.subinsert2();
                }
        }  
 
        
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(courseSelectM.underComCourse=="Bsc (Honurs) in Computer Science"){
        setlistCS();
        jButton4.setVisible(false);
        System.out.println("Intake" +MStudentDe.intakeBtnGroup1);
        if(MStudentDe.intakeBtnGroup1=="February"){
            Sem2Sublist.setVisible(false);
            jLabel3.setVisible(false);
        }
        else if(MStudentDe.intakeBtnGroup1=="July"){
            setlistCS2();
        }
        
       // }
    }//GEN-LAST:event_jButton4ActionPerformed
    }
    /**
     * @param  the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Sem1SubList;
    private javax.swing.JList<String> Sem2Sublist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
